config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get 'approval_request', to: 'static_pages#approval_request'
  get '/how_to_channel', to: 'static_pages#how_to_channel'
  get '/contact', to: 'static_pages#contact'
  get 'requests/new'
  root 'boards#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/signup',     to: 'users#new'
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get '/requests',   to: 'requests#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boards do
    resources :game_recruitments, only: [:new, :create, :show] do
      resources :requests, only: [:new, :create, :show, :update, :destroy]
    end
    resources :comments, only: [:new, :create, :show]
  end
end

app/models/game_recruitment.rb
class GameRecruitment < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_many :request
  validates :user_id, presence: true
  validates :board_id, presence: true
  validates :game_title, presence: true
  validates :channel_name, presence: true, length: { maximum: 32 }
  validates :description, length: { maximum: 30 }
  validates :num_players, length: { maximum: 8 }
end

app/controllers/game_recruitments_controller.rb
class GameRecruitmentsController < ApplicationController

  def new
    @game_recruitment = GameRecruitment.new
  end

  def create
    @board = Board.find(params[:board_id])
    @game_recruitment = @board.game_recruitments.build(game_recruitment_params)
    @game_recruitment.user = current_user
    if @game_recruitment.save
      # @game_recruitmentの保存が成功した場合の処理
      redirect_to board_path(@board), notice: "募集が作成されました"
    else
      # @game_recruitmentの保存が失敗した場合の処理
      redirect_to boards_path, alert: "募集の作成に失敗しました"
      puts @game_recruitment.errors.full_messages
    end
  end

  def show
    @board = Board.find(params[:board_id])
    @game_recruitment = GameRecruitment.find(params[:id])
    @request = Request.find_by(game_recruitment_id: @game_recruitment.id)
    # リクエストが許可されたらhiddenがtrueになる
    if @request && @request.hidden == true
      # チャンネル名を表示する処理
      @channel_name = @game_recruitment.channel_name
    else
      # チャンネル名が存在しない場合の処理
      @channel_name = "リクエスト申請が許可されたユーザーにのみ表示されます。"
    end
  end

  private
  def game_recruitment_params
    params.require(:game_recruitment).permit(:game_title, :description, :num_players, :channel_name)
  end
end

app/helpers/game_recruitment_helper.rb
module GameRecruitmentHelper
end

app/views/game_recruitments/_new.html.erb
<!-- 募集作成フォーム -->
<% provide(:title, 'Create Game_Recruitment') %>
<h2>募集作成</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 game-recruitment-form">
    <%= form_with(model: [@board, GameRecruitment.new]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :ゲームモード %>
        <%= f.select :game_title, options_for_select(['ナワバリバトル', 'バンカラマッチ', 'サーモンラン', 'ナワバトラー']), { include_blank: false }, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :チャンネル名 %>
        <%= f.text_field :channel_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :詳細 %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :募集人数 %>
        <%= f.number_field :num_players, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "募集開始", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/game_recruitments/show.html.erb
<!-- 募集詳細表示画面 -->
<% provide(:title, @game_recruitment.game_title) %>
<div class="row">
  <aside class="col-md-4 game-recruitment-info">
    <section class="user_info">
      <h1>
        ゲームモード：<%= @game_recruitment.game_title %>
      <h1>
      <!-- リクエストが許可された場合にのみ表示 -->
      <h2>チャンネル名：<%= @channel_name %></h2>
      <!-- ここまで -->
      <p>
        詳細コメント：<%= @game_recruitment.description %><br>
        募集ユーザー：<%= @game_recruitment.user.name %><br>
        募集人数：<%= @game_recruitment.num_players %>
      </p>
    </section>
    <% if logged_in? %>
      <% if @game_recruitment.user_id == current_user.id %>
        <h2 class="approval_requests">
          参加希望のユーザーから<%= link_to "リクエスト", board_game_recruitment_request_path(@board, @game_recruitment) %>申請が届いたようです！</br>
          今すぐ確認してみましょう。
        </h2>
      <% else %>
        <%= render partial: 'requests/new' %>
      <% end %>
    <% else %>
      <%= link_to "ログイン", login_path %> することで参加リクエストの申請が可能になります。
    <% end %>
  </aside>
</div>