config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get 'approval_request', to: 'static_pages#approval_request'
  get '/how_to_channel', to: 'static_pages#how_to_channel'
  get '/contact', to: 'static_pages#contact'
  get 'requests/new'
  root 'boards#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/signup',     to: 'users#new'
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get '/requests',   to: 'requests#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boards do
    resources :game_recruitments, only: [:new, :create, :show] do
      resources :requests, only: [:new, :create, :show, :update, :destroy]
    end
    resources :comments, only: [:new, :create, :show]
  end
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :game_recruitments 
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = "掲示板の作成が完了しました!"
      redirect_to root_path
    else
      render 'board/index', status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    # ボードに関連するスレッド（ゲーム募集とコメント）を取得し、作成日時で並び替え
    @threads = (GameRecruitment.where(board_id: @board.id) + Comment.where(board_id: @board.id)).sort_by(&:created_at).reverse
  end

  def destroy; end

  private
  def board_params
    params.require(:board).permit(:title)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.erb
<!-- 掲示板一覧 タイトルのみリスト表示 -->
<% provide(:title, 'All boards') %>
<h1 class="title-with-image">掲示板一覧</h1>
<!-- 掲示板タイトル・作成日時を一覧で表示 -->
<div class="board-lists">
  <% @boards.each do |board| %>
    <div class="board-list">
      <li>
        <%= link_to board.title, board %>
        <span class="timestamp">
          <%= time_ago_in_words(board.created_at) %>前に作成
        </span>
      </li>
    </div>
  <% end %>
</div>

<!-- ログイン済みユーザーのみ新規掲示板作成が可能になる -->
<% if logged_in? %>
  <div class="board-new">
    <%= link_to "新規掲示板作成", new_board_path %>
  </div>
<% else %>
<%= link_to "ログイン", login_path %>することで新規掲示板の作成が可能になります。
<% end %>

app/views/boards/new.html.erb
<!-- 新規掲示板作成フォーム -->
<% provide(:title, 'Create board') %>
<div class="create-board-container">
  <h1 class="create-board-title">掲示板作成</h1>

  <!-- タイトル入力フォーム・作成ボタン -->
  <div class="create-board-form">
    <%= form_with(model: @board) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :タイトル %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.submit "作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<!-- 掲示板詳細 コメント・ゲーム募集が一覧で表示 -->
<h1><%= @board.title %></h1>
<!-- if文でまずコメント・募集あるか→あればそれを表示、なければ"投稿がありません"と表示 -->
<!-- ここに掲示板の中身、コメントと募集表示 -->
<!-- コメントとゲーム募集の一覧の表示 -->
<table class="thread-table">
  <thead>
    <tr>
      <th>投稿者</th>
      <th class="content-cell">内容</th>
      <th>詳細</th>
      <th class="timestamp-cell">投稿日時</th>
    </tr>
  </thead>
  <tbody>
    <!-- コメントと募集で表示内容を変更する -->
    <!-- コメントの場合→コメントしたユーザー・コメント本文・・作成日時 -->
    <!-- 募集の場合→募集したユーザー・募集内容文・詳細表示（クリックで募集詳細画面に遷移）・作成日時 -->
    <% @threads.each do |thread| %>
      <% if thread.is_a?(Comment) %>
        <% comment = thread %>
        <tr>
          <td><%= comment.user.name %></td>
          <td class="thread-content"><%= comment.content %></td>
          <td> </td>
          <td><%= comment.created_at %></td>
        </tr>
      <% elsif thread.is_a?(GameRecruitment) %>
        <% game_recruitment = thread %>
        <tr>
          <td><%= game_recruitment.user.name %></td>
          <td class="thread-content"><%= game_recruitment.description %></td>
          <td><%= link_to "詳細表示", board_game_recruitment_path(@board, game_recruitment) %></td>
          <td><%= game_recruitment.created_at %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<!-- ログイン済みユーザーのみ新規コメント・新規募集の作成が可能になる -->
<% if logged_in? %>
  <!-- 一番下にコメント作成フォーム・募集作成ボタン→フォームに飛ぶ -->
  <%= render partial: 'comments/new' %>
  <%= render partial: 'game_recruitments/new' %>
  <!-- 表示のイメージとしてはラインのような感じ、表示内容はユーザーの名前、アイコン、内容、タイムスタンプ -->
<% else %>
  <%= link_to "ログイン", login_path %>することでコメントと募集の作成が可能になります。
<% end %>