config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get 'approval_request', to: 'static_pages#approval_request'
  get '/how_to_channel', to: 'static_pages#how_to_channel'
  get '/contact', to: 'static_pages#contact'
  get 'requests/new'
  root 'boards#index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/signup',     to: 'users#new'
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get '/requests',   to: 'requests#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boards do
    resources :game_recruitments, only: [:new, :create, :show] do
      resources :requests, only: [:new, :create, :show, :update, :destroy]
    end
    resources :comments, only: [:new, :create, :show]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="background-image-left"></div>
  <div class="footer-content">
    <nav>
      <ul>
        <li><%= link_to "チャンネル機能の使用方法",  how_to_channel_path %></li>
        <li><%= link_to "お問い合わせ", contact_path %></li>
      </ul>
    </nav>
  </div>
  <div class="background-image-right"></div>
</footer>

app/views/layouts/_header.html.erb
<!-- ヘッダー -->
<header class="navbar navbar-fixed-top navbar-inverse header-bg">
  <div class="header-content">
    <!-- タイトル（アプリ名） -->
    <h1 class="title"><%= link_to "スプラ３フレンド募集掲示板", about_path, id: "logo" %></h1>
    <button class="hamburger-menu" type="button" aria-expanded="false">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- ヘッダー内メニュー -->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '掲示板一覧', root_path %></li>
        <!-- ログイン済みユーザーのみアカウント・新規掲示板作成・リクエスト表示 -->
        <% if logged_in? %>
          <li><%= link_to '新規掲示板作成', new_board_path %></li>
          <li class="dropdown">
            <a href="#" id="account" class="dropdown-toggle">
              アカウント <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path,
                                  data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <!-- 未ログイン時、新規登録・ログイン表示 -->
          <li><%= link_to '新規登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>スプラ３フレンド募集掲示板</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container" style="margin-top: 150px;">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>